version: "3.7"

services:

  flask:
    build: ./backend
    container_name: flask_dev
    restart: always
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  angular:
    build: ./frontend
    container_name: angular_dev
    restart: always
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app