version: '3.7'

services:

  # https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME: root
    #   - MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /var/lib/mongodb:/data/db
    ports:
      - 27017:27017  # 27017-27019:27017-27019
    entrypoint: mongod --bind_ip_all

  flask:
    build: ./backend
    container_name: flask
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/decsDev
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    links:
      - mongo

  angular:
    build: ./frontend
    container_name: angular
    # https://codinglatte.com/posts/angular/using-os-environment-variables-in-angular-with-docker/
    # environment:
    #   - REST_API_URL=http://localhost:5000
    #   - BROWSER_SESSION_KEY=user
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    links:
      - flask
