version: '3.7'

services:

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-prod
    ports:
      - '80:80'

  flask:
    build: ./backend
    hostname: flask-prod
    container_name: flask
    restart: always
    environment:
      - MONGO_URI=mongodb://mesinesp:mesinesp@bsccnio01.bsc.es:27017/BvSalud
    command: uwsgi app.ini
