version: "3.7"

services:

  flask:
    build: ./backend
    container_name: flask_dev
    restart: always
    # ports:
    #   - 5000:5000
    environment:
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    volumes:
      - ./backend:/app

  angular:
    build: ./frontend
    container_name: angular_dev
    restart: always
    # ports:
    #   - 4201:4200
    command: ng serve --host 0.0.0.0
    volumes:
      - ./frontend:/app