version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - 27017:27017
    entrypoint: mongod --bind_ip_all

  flask:
    build: ./backend
    container_name: flask
    links:
      - mongo
    environment:

      # Enables the debug mode
      - FLASK_ENV=development

      # [Option A] Absolute development mode without risks of damaging the real MongoDB
      # First, you should run mongorestore --gzip (from the latest backup to your localhost),
      # so you have available the databases and collections used by the API.
      # - MONGO_URI=mongodb://mongo/BvSalud
      # - MONGO_DATASETS_URI=mongodb://mongo/datasets

      # [Option A] Development against the real remote database
      # First, you should have a VPN connection tunnel stablished to reach the mongod service remotely.
      # $ sudo apt update && sudo apt install -y openfortivpn && sudo openfortivpn gw.bsc.es:443 -u USERNAME
      - MONGO_URI=mongodb://bsccnio01.bsc.es/BvSalud
      - MONGO_DATASETS_URI=mongodb://bsccnio01.bsc.es/datasets
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    

  angular:
    build: ./frontend
    container_name: angular
    links:
      - flask
    environment:
      - APP_API_URL=http://localhost:5000
      - APP_BROWSER_STORAGE_KEY=devMesinesp
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
