version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    # volumes:
    #   - ./flask:/app

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
  
  angular:
    build: ./frontend
    container_name: frontend
    restart: always
    # volumes:
    #   # - /app/node_modules
    #   - ./frontend:/app
    ports:
      - 4201:4200