version: '3.7'

services:

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: angular-prod
    env_file:
      - .env.prod
    ports:
      - '80:80'

  flask:
    build: ./backend
    container_name: flask-prod
    restart: always
    env_file:
      - .env.prod
    command: uwsgi app.ini
