version: '3.7'
services:
  mongo:
    image: mongo
    container_name: indexer-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=dev
    volumes:
      - /var/lib/mongodb:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017-27019:27017-27019
    entrypoint: mongod --bind_ip_all

  flask:
    container_name: indexer-backend
    depends_on:
      - mongo
    build: ./backend
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=mongo
      - MONGO_DATABASE=dev
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    command: flask run --host 0.0.0.0

  angular:
    container_name: indexer-frontend
    depends_on:
      - flask
    build: ./frontend
    environment:
      - APP_API_URL=http://localhost:5000
      - APP_BROWSER_STORAGE_KEY=indexer
    volumes:
      - ./frontend:/app
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0
