version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - 27017:27017
    entrypoint: mongod --bind_ip_all

  flask:
    build: ./backend
    container_name: flask
    env_file:
      - .env
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    links:
      - mongo

  angular:
    build: ./frontend
    container_name: angular
    env_file:
      - .env
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
    links:
      - flask
