version: '3.7'

services:

  flask:
    build: ./backend
    container_name: flask
    restart: always
    environment:
      - MONGO_URI=mongodb://mesinesp:mesinesp@bsccnio01.bsc.es:27017/BvSalud
      - JWT_SECRET_KEY=secret
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  angular:
    build: ./frontend
    container_name: angular
    restart: always
    environment:
      - REST_API_URL=http://localhost:5000
    command: ng serve --host 0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
