version: "3.7"

services:

  flask:
    build: ./backend
    container_name: flask
    restart: always
    expose:
      - 8080
    command: uwsgi app.ini

  nginx:
    build: ./server
    container_name: nginx
    restart: always
    ports:
      - "8080:80"

  angular:
    build: ./frontend
    container_name: angular
    restart: always
    ports:
      - 4201:4200
    command: ng serve --host 0.0.0.0 --disableHostCheck

    # expose:
    #   - 80
    # command: nginx -g daemon off;