services:

  flask:
    container_name: indexer_flask
    build: ./backend
    env_file:
      - .env/flask.production.env
    ports:
      - 5000:5000
    command: flask run --host 0.0.0.0
    # ports:
    #   - 8080:8080
    # command: uwsgi app.ini
    restart: always

  angular:
    container_name: indexer_angular
    build: ./frontend
    ports:
      - 80:80
    restart: always
